-- 여기에 테이블을 정의하세요.
-- lib/db.ts의 getDB()가 앱 시작 시 이 파일을 자동으로 실행합니다.
--
-- 예시:
-- CREATE TABLE IF NOT EXISTS items (
--   id INTEGER PRIMARY KEY AUTOINCREMENT,
--   title TEXT NOT NULL,
--   status TEXT NOT NULL DEFAULT 'active',
--   created_at TEXT NOT NULL DEFAULT (datetime('now', 'localtime'))
-- );
